name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Godkänt
      id: godkant
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Godkänt
        setup-command: npm install
        command: NODE_OPTIONS=--experimental-vm-modules npm test
        timeout: 10
        max-score: 2
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        GODKANT_RESULTS: "${{steps.godkant.outputs.result}}"
      with:
        runners: godkant
